In [5]:
import pandas as pd
from pathlib import Path
from or_llm_agent.utils import get_project_root

In [6]:
dir_path_solutions = Path(f"{get_project_root()}/solutions")

In [8]:
# After the loop finishes:
df = pd.read_csv(f"{dir_path_solutions}/eval/run_eval_final.csv")

In [10]:
df

    problem_id version_tag  target_answer  successful_solutions           mae
0     BWOR-022         v00      -3.170086                     1  7.298556e-14
1     BWOR-063         v00      16.000000                     0  1.000000e+01
2     BWOR-049         v00    1490.000000                     1  0.000000e+00
3     BWOR-055         v00    1500.000000                     1  0.000000e+00
4     BWOR-069         v00     500.000000                     1  0.000000e+00
..         ...         ...            ...                   ...           ...
241   BWOR-080         v13  937151.785700                     1  1.524371e-11
242   BWOR-025         v13      81.000000                     0  1.000000e+01
243   BWOR-035         v13      20.548322                     0  1.000000e+01
244   BWOR-019         v13       9.260000                     1  0.000000e+00
245   BWOR-072         v13       1.200000                     0  1.000000e+01

[246 rows x 5 columns]

In [23]:
df["nummerical_answer"] = 1 
df.loc[df["target_answer"].isnull(), "nummerical_answer"] = 0
df.loc[df["target_answer"].isna(), "nummerical_answer"] = 0
df["valid_mae_answer"] = 1 
df.loc[df["mae"]>0.5, "valid_mae_answer"] = 0
df["valid_mae"] = df["mae"].values 
df.loc[df["valid_mae_answer"]==0, "valid_mae"] = 0

In [24]:
df_g = df[["version_tag", "successful_solutions", "nummerical_answer", "valid_mae_answer", "mae", "valid_mae"]].groupby(by="version_tag").sum()
df_g["mae"] = df_g["mae"]/df_g["nummerical_answer"]
df_g["valid_mae"] = df_g["valid_mae"]/df_g["valid_mae_answer"]

In [25]:
df_g

,successful_solutions,nummerical_answer,valid_mae_answer,mae,valid_mae
version_tag,,,,,
v0,62,80,60,2.750288,0.000383
v00,54,80,53,3.625386,0.000583
v13,59,80,57,3.126227,0.001722

In [3]:
@dataclass
class PipelineResult:
    problem_id: str
    difficulty: str
    domain: str
    version_tag: str
    target_answer: float
    markdown_model: str
    python_code: str
    exec_result: ExecutionResult

In [59]:
# Setup
MODEL = LiteLlm(
    model="openai/qwen38_q3",
    api_base="http://localhost:8000/v1",
    api_key="not-needed",
    temperature=0.7
)

In [4]:
dir_path = Path(f"{get_project_root()}/solutions/result")
files = [f for f in dir_path.iterdir() if f.is_file()]

In [5]:
str(files[0])

'/mnt/datafast/Development/or-llm-agent/solutions/result/BWOR-020_v13.json'

In [6]:
problems_versions = set([((str(f).split("/")[-1]).split(".")[0]) for f in files])
list_problems_versions = []
for pv in problems_versions:
    list_problems_versions.append([pv, pv.split("_")[0], pv.split("_")[-1], int(pv.split("_")[-1].replace("v", "")) ])
list_problems_versions

[['BWOR-034_v7', 'BWOR-034', 'v7', 7],
 ['BWOR-079_v18', 'BWOR-079', 'v18', 18],
 ['BWOR-072_v2', 'BWOR-072', 'v2', 2],
 ['BWOR-020_v2', 'BWOR-020', 'v2', 2],
 ['BWOR-069_v8', 'BWOR-069', 'v8', 8],
 ['BWOR-007_v2', 'BWOR-007', 'v2', 2],
 ['BWOR-028_v2', 'BWOR-028', 'v2', 2],
 ['BWOR-037_v18', 'BWOR-037', 'v18', 18],
 ['BWOR-020_v9', 'BWOR-020', 'v9', 9],
 ['BWOR-059_v18', 'BWOR-059', 'v18', 18],
 ['BWOR-024_v11', 'BWOR-024', 'v11', 11],
 ['BWOR-055_v16', 'BWOR-055', 'v16', 16],
 ['BWOR-040_v11', 'BWOR-040', 'v11', 11],
 ['BWOR-065_v5', 'BWOR-065', 'v5', 5],
 ['BWOR-062_v2', 'BWOR-062', 'v2', 2],
 ['BWOR-007_v10', 'BWOR-007', 'v10', 10],
 ['BWOR-043_v14', 'BWOR-043', 'v14', 14],
 ['BWOR-024_v19', 'BWOR-024', 'v19', 19],
 ['BWOR-062_v8', 'BWOR-062', 'v8', 8],
 ['BWOR-009_v14', 'BWOR-009', 'v14', 14],
 ['BWOR-077_v8', 'BWOR-077', 'v8', 8],
 ['BWOR-021_v14', 'BWOR-021', 'v14', 14],
 ['BWOR-067_v3', 'BWOR-067', 'v3', 3],
 ['BWOR-057_v4', 'BWOR-057', 'v4', 4],
 ['BWOR-006_v7', 'BWOR-006', 'v7', 7],
 ['BWOR-068_v5', 'BWOR-068', 'v5', 5],
 ['BWOR-032_v8', 'BWOR-032', 'v8', 8],
 ['BWOR-070_v0', 'BWOR-070', 'v0', 0],
 ['BWOR-064_v3', 'BWOR-064', 'v3', 3],
 ['BWOR-011_v18', 'BWOR-011', 'v18', 18],
 ['BWOR-053_v16', 'BWOR-053', 'v16', 16],
 ['BWOR-008_v10', 'BWOR-008', 'v10', 10],
 ['BWOR-009_v3', 'BWOR-009', 'v3', 3],
 ['BWOR-020_v15', 'BWOR-020', 'v15', 15],
 ['BWOR-050_v1', 'BWOR-050', 'v1', 1],
 ['BWOR-061_v1', 'BWOR-061', 'v1', 1],
 ['BWOR-053_v13', 'BWOR-053', 'v13', 13],
 ['BWOR-030_v0', 'BWOR-030', 'v0', 0],
 ['BWOR-033_v6', 'BWOR-033', 'v6', 6],
 ['BWOR-034_v8', 'BWOR-034', 'v8', 8],
 ['BWOR-030_v5', 'BWOR-030', 'v5', 5],
 ['BWOR-012_v11', 'BWOR-012', 'v11', 11],
 ['BWOR-006_v6', 'BWOR-006', 'v6', 6],
 ['BWOR-012_v1', 'BWOR-012', 'v1', 1],
 ['BWOR-077_v19', 'BWOR-077', 'v19', 19],
 ['BWOR-008_v15', 'BWOR-008', 'v15', 15],
 ['BWOR-009_v11', 'BWOR-009', 'v11', 11],
 ['BWOR-054_v16', 'BWOR-054', 'v16', 16],
 ['BWOR-065_v15', 'BWOR-065', 'v15', 15],
 ['BWOR-069_v17', 'BWOR-069', 'v17', 17],
 ['BWOR-029_v7', 'BWOR-029', 'v7', 7],
 ['BWOR-066_v10', 'BWOR-066', 'v10', 10],
 ['BWOR-071_v1', 'BWOR-071', 'v1', 1],
 ['BWOR-074_v15', 'BWOR-074', 'v15', 15],
 ['BWOR-073_v12', 'BWOR-073', 'v12', 12],
 ['BWOR-020_v13', 'BWOR-020', 'v13', 13],
 ['BWOR-068_v9', 'BWOR-068', 'v9', 9],
 ['BWOR-048_v19', 'BWOR-048', 'v19', 19],
 ['BWOR-003_v0', 'BWOR-003', 'v0', 0],
 ['BWOR-067_v14', 'BWOR-067', 'v14', 14],
 ['BWOR-049_v4', 'BWOR-049', 'v4', 4],
 ['BWOR-036_v7', 'BWOR-036', 'v7', 7],
 ['BWOR-012_v9', 'BWOR-012', 'v9', 9],
 ['BWOR-049_v3', 'BWOR-049', 'v3', 3],
 ['BWOR-061_v17', 'BWOR-061', 'v17', 17],
 ['BWOR-024_v10', 'BWOR-024', 'v10', 10],
 ['BWOR-046_v3', 'BWOR-046', 'v3', 3],
 ['BWOR-077_v12', 'BWOR-077', 'v12', 12],
 ['BWOR-065_v1', 'BWOR-065', 'v1', 1],
 ['BWOR-074_v19', 'BWOR-074', 'v19', 19],
 ['BWOR-010_v16', 'BWOR-010', 'v16', 16],
 ['BWOR-031_v15', 'BWOR-031', 'v15', 15],
 ['BWOR-062_v6', 'BWOR-062', 'v6', 6],
 ['BWOR-057_v0', 'BWOR-057', 'v0', 0],
 ['BWOR-036_v17', 'BWOR-036', 'v17', 17],
 ['BWOR-050_v4', 'BWOR-050', 'v4', 4],
 ['BWOR-005_v14', 'BWOR-005', 'v14', 14],
 ['BWOR-055_v13', 'BWOR-055', 'v13', 13],
 ['BWOR-025_v17', 'BWOR-025', 'v17', 17],
 ['BWOR-011_v11', 'BWOR-011', 'v11', 11],
 ['BWOR-055_v5', 'BWOR-055', 'v5', 5],
 ['BWOR-018_v4', 'BWOR-018', 'v4', 4],
 ['BWOR-032_v7', 'BWOR-032', 'v7', 7],
 ['BWOR-011_v16', 'BWOR-011', 'v16', 16],
 ['BWOR-015_v19', 'BWOR-015', 'v19', 19],
 ['BWOR-034_v6', 'BWOR-034', 'v6', 6],
 ['BWOR-041_v17', 'BWOR-041', 'v17', 17],
 ['BWOR-082_v0', 'BWOR-082', 'v0', 0],
 ['BWOR-043_v18', 'BWOR-043', 'v18', 18],
 ['BWOR-049_v6', 'BWOR-049', 'v6', 6],
 ['BWOR-044_v4', 'BWOR-044', 'v4', 4],
 ['BWOR-074_v9', 'BWOR-074', 'v9', 9],
 ['BWOR-012_v12', 'BWOR-012', 'v12', 12],
 ['BWOR-049_v13', 'BWOR-049', 'v13', 13],
 ['BWOR-056_v12', 'BWOR-056', 'v12', 12],
 ['BWOR-025_v9', 'BWOR-025', 'v9', 9],
 ['BWOR-079_v13', 'BWOR-079', 'v13', 13],
 ['BWOR-044_v5', 'BWOR-044', 'v5', 5]]

In [7]:
with open(Path(f"{get_project_root()}/problems/data/test.jsonl"), "r", encoding="utf-8") as f:
    problems = [json.loads(line) for line in f if line.strip()]

problem_dict = {p["id"]: p for p in problems if "id" in p}

In [8]:
problem_dict

{'BWOR-001': {'id': 'BWOR-001',
  'en_question': '\n    A candy factory uses raw materials A, B, and C to produce three different brands of candy: Brand X, Brand Y, and Brand Z. The content proportions of A, B, and C in each brand, the costs of the raw materials, the monthly usage limits for each raw material, as well as the unit processing cost and selling price of each candy brand are shown in Table 1-17.The question is: How many kilograms of each brand of candy should the factory produce each month in order to maximize its profit?Please formulate a linear programming mathematical model for this problem.\n\\begin{table}[h]\n    \\centering\n    \\caption{Raw Materials and Candy Production Data}\n    \\renewcommand{\\arraystretch}{1.2}\n    \\begin{tabular}{c|ccc|c|c}\n        \\toprule\n        Raw Materials & X & Y & Z & Raw Material Cost(dollar/kg) & Monthly Usage Limit(kg) \\\\\n        \\midrule\n        A & $\\geq 60\\%$ & $\\geq 30\\%$ & & 2.00 & 2000 \\\\\n        B & & & & 1.50 & 2500 \\\\\n        C & $\\leq 20\\%$ & $\\leq 50\\%$ & $\\leq 60\\%$ & 1.00 & 1200 \\\\\n        \\midrule\n        Processing Cost(dollar/kg) & 0.50 & 0.40 & 0.30 & & \\\\\n        Selling Price(dollar/kg) & 3.40 & 2.85 & 2.25 & & \\\\\n        \\bottomrule\n    \\end{tabular}\n\\end{table}\n',
  'cn_question': '\n    某糖果厂用原料 A、B、C 加工成三种不同牌号的糖果甲、乙、丙。已知各种牌号糖果中 A、B、C 含量、原料成本、各种原料的每月限制用量、三种牌号糖果的单位加工费及售价，如表 1-17 所示。问该厂每月生产这三种牌号糖果各多少 kg，才能使其获利最大。试建立这个问题的线性规划的数学模型。\n\\begin{table}[h]\n    \\centering\n    \\caption{原料及糖果生产数据}\n    \\renewcommand{\\arraystretch}{1.2}\n    \\begin{tabular}{c|ccc|c|c}\n        \\toprule\n        原料 & 甲 & 乙 & 丙 & 原料成本(元/kg) & 每月限制用量(kg) \\\\\n        \\midrule\n        A & $\\geq 60\\%$ & $\\geq 30\\%$ & & 2.00 & 2000 \\\\\n        B & & & & 1.50 & 2500 \\\\\n        C & $\\leq 20\\%$ & $\\leq 50\\%$ & $\\leq 60\\%$ & 1.00 & 1200 \\\\\n        \\midrule\n        加工费(元/kg) & 0.50 & 0.40 & 0.30 & & \\\\\n        售价(元/kg) & 3.40 & 2.85 & 2.25 & & \\\\\n        \\bottomrule\n    \\end{tabular}\n\\end{table}\n',
  'answer': 5450.0,
  'solution_status': 'optimal',
  'domain': 'blending',
  'problem_type': 'LP',
  'difficulty': 'Medium'},
 'BWOR-002': {'id': 'BWOR-002',
  'en_question': '\n    A livestock farm raises animals for sale. It is required that each animal must receive at least 700g of protein, 30g of minerals, and 100mg of vitamins per day. There are five types of feed available for selection. The nutritional content per kilogram and the unit price of each type of feed are shown in Table 1-22.\n\n\\begin{table}[h]\n    \\centering\n    \\caption{Nutritional Content and Price of Feed}\n    \\renewcommand{\\arraystretch}{1.2}\n    \\begin{tabular}{c|c|c|c|c}\n        \\toprule\n        Feed & Protein (g) & Minerals (g) & Vitamins (mg) & Price (dollar/kg) \\\\\n        \\midrule\n        1 & 3 & 1.0 & 0.5 & 0.2 \\\\\n        2 & 2 & 0.5 & 1.0 & 0.7 \\\\\n        3 & 1 & 0.2 & 0.2 & 0.4 \\\\\n        4 & 6 & 2.0 & 2.0 & 0.3 \\\\\n        5 & 18 & 0.5 & 0.8 & 0.8 \\\\\n        \\bottomrule\n    \\end{tabular}\n\\end{table}\n\nThe goal is to determine a feed selection plan that both meets the nutritional requirements for animal growth and minimizes the cost.\n',
  'cn_question': '\n    某饲养场饲养动物出售，设每头动物每天至少需 700g 蛋白质、30g 矿物质、100mg 维生素。现有五种饲料可供选用，各种饲料每 kg 营养成分含量及单位价格如表 1-22 所示。\n\n\\begin{table}[h]\n    \\centering\n    \\caption{饲料营养成分及价格}\n    \\renewcommand{\\arraystretch}{1.2}\n    \\begin{tabular}{c|c|c|c|c}\n        \\toprule\n        饲料 & 蛋白质 (g) & 矿物质 (g) & 维生素 (mg) & 价格 (元/kg) \\\\\n        \\midrule\n        1 & 3 & 1.0 & 0.5 & 0.2 \\\\\n        2 & 2 & 0.5 & 1.0 & 0.7 \\\\\n        3 & 1 & 0.2 & 0.2 & 0.4 \\\\\n        4 & 6 & 2.0 & 2.0 & 0.3 \\\\\n        5 & 18 & 0.5 & 0.8 & 0.8 \\\\\n        \\bottomrule\n    \\end{tabular}\n\\end{table}\n\n要求确定既满足动物生长的营养需要，又使费用最省的选用饲料的方案。\n',
  'answer': 32.43,
  'solution_status': 'optimal',
  'domain': 'blending',
  'problem_type': 'LP',
  'difficulty': 'Medium'},
 'BWOR-003': {'id': 'BWOR-003',
  'en_question': '\n    Hongyin Company has committed to providing the following loan amounts at the beginning of each year for a construction project over a period of four years starting from 2003:\n\\begin{itemize}\n    \\item Year 2003 — 100 thousand dollars\n    \\item Year 2004 — 150 thousand dollars\n    \\item Year 2005 — 120 thousand dollars\n    \\item Year 2006 — 110 thousand dollars\n\\end{itemize}\n\n All the above loan funds must be raised before the end of 2002. However, in order to make full use of the funds, any surplus (after meeting the annual loan amounts) can be invested in the following projects:\n\n\\begin{enumerate}\n    \\item At the beginning of 2003, purchase Bond A, with a term of 3 years. Upon maturity, the total return (principal and interest) will be 140\\% of the investment. The purchase is limited to 60 thousand dollars. \n    \\item At the beginning of 2003, purchase Bond B, with a term of 2 years. Upon maturity, the total return (principal and interest) will be 125\\% of the investment. The purchase is limited to 90 thousand dollars. \n    \\item At the beginning of 2004, purchase Bond C, with a term of 2 years. Upon maturity, the total return (principal and interest) will be 130% of the investment. The purchase is limited to 50 thousand dollars. \n    \\item At the beginning of each year, any amount of surplus funds may be deposited in a bank account at an annual interest rate of 4%, with withdrawal at the end of the same year. \n\\end{enumerate}\n\n Question:How should Hongyin Company utilize the raised funds to ensure that the total amount needed to be raised at the end of 2002 is minimized? \n',
  'cn_question': '\n    宏银公司承诺为某建设项目从 2003 年起的 4 年中每年年初分别提供以下数额贷款：\n\\begin{itemize}\n    \\item 2003 年——100 万元\n    \\item 2004 年——150 万元\n    \\item 2005 年——120 万元\n    \\item 2006 年——110 万元\n\\end{itemize}\n\n以上贷款资金均需于 2002 年底前筹集。但为了充分发挥这笔资金的作用，在满足每年贷款额情况下，可将多余资金分别用于下列投资项目：\n\n\\begin{enumerate}\n    \\item 于 2003 年年初购买 A 种债券，期限 3 年，到期后本息合计为投资额的 140\\%，但限购 60 万元；\n    \\item 于 2003 年年初购买 B 种债券，期限 2 年，到期后本息合计为投资额的 125\\%，但限购 90 万元；\n    \\item 于 2004 年年初购买 C 种债券，期限 2 年，到期后本息合计为投资额的 130\\%，但限购 50 万元；\n    \\item 于每年年初将任意数额的资金存放于银行，年息 4\\%，于每年年底取出。\n\\end{enumerate}\n\n求宏银公司应如何运用好这笔筹集到的资金，使 2002 年底需筹集的资金数额最少。\n',
  'answer': 420.3957101,
  'solution_status': 'optimal',
  'domain': 'finance',
  'problem_type': 'LP',
  'difficulty': 'Medium'},
 'BWOR-004': {'id': 'BWOR-004',
  'en_question': '\n At the beginning of the year, Hongdou Garment Factory launched a new fashion product. Based on experience and market research, the predicted demand for this product over the next six months is as follows: \n January:3,000 units, February:3,600 units, March:4,000 units, April: 4,600 units, May:4,800 units, June:5,000 units \n Each unit requires 4 hours of skilled labor and 150 dollars worth of raw materials to produce. The selling price is 240 dollars per unit. \n At the beginning of January, the factory has 80 skilled workers, each working 160 hours per month. To meet production needs, the factory can recruit and train new workers. Training a new worker takes 50 hours of a skilled worker’s time for instruction, and the training period lasts one month, after which the trainee can become a skilled worker. Skilled workers are paid 2,000 dollars per month. Trainees receive a living allowance of 800 dollars during the training month. After completing training, new workers receive the same salary and work efficiency as skilled workers. Each month, 2\\% of skilled workers (including those newly trained and on the job for at least one month) leave due to various reasons. \n The factory starts the year with 400 units of inventory and requires that the ending inventory in June not exceed 100 units. Additionally, if garments are not delivered in the month of production, they incur a storage cost of 10 dollars per unit per month. Design a labor and production plan for the factory that satisfies the monthly and end-of-June inventory requirements, while maximizing the total revenue from January to June.\n',
  'cn_question': '\n红豆服装厂新推出一款时装，根据经验和市场调查，预测今后6个月对该款时装的需求为：\n1 月——3 000 件，2 月——3 600 件，3 月——4 000 件，4 月——4 600 件，5 月——4 800 件，6 月——5 000 件。\n生产每件需熟练工人工作 4h，耗用原材料 150 元。售价为 240 元/件。该厂 1 月初有熟练工 80 人，每人每月工作 160h。为适应生产需要，该厂可招收新工人培训，\n但培训一名新工人需占用熟练工人 50h 用于指导操作，培训期为一个月，结束后即可上岗。\n熟练工人每月工资 2 000 元，新工人培训期给予生活补贴 800 元，转正后工资与生产效率同熟练工人。\n又熟练工人（含转正一个月后的新工人）每月有 2\\% 因各种原因离职。已知该厂年初加工出 400 件该款时装作为库存，\n要求 6 月末库存不超过 100 件。又每月生产出来的时装如不在当月交货，库存费用为每件每月 10 元。\n试为该厂设计一个满足月及 6 月末存货要求，又使 1—6 月总收入为最大的劳动与生产方案。\n',
  'answer': 1000613.89,
  'solution_status': 'optimal',
  'domain': 'production_planning',
  'problem_type': 'MIP',
  'difficulty': 'Medium'},
 'BWOR-005': {'id': 'BWOR-005',
  'en_question': '\n A cargo ship has three compartments: front, middle, and rear. Their volumes and maximum allowable loads are shown in \\ref{table1-24}. \n There are three types of cargo to be shipped, with data shown in  \\ref{table1-25}.\n\n\\begin{table}[h]\n    \\centering\n    \\caption{Maximum Allowable Load and Volume}\n    \\label{table1-24}\n    \\begin{tabular}{|c|c|c|}\n        \\hline\n        \\textbf{Item} & \\textbf{Front Compartment} & \\textbf{Middle Compartment} & \\textbf{Rear Compartment} \\\\\n        \\hline\n        Max Allowable Load (t) & 2000 & 3000 & 1500 \\\\\n        \\hline\n        Volume ($m^3$) & 4000 & 5000 & 1500 \\\\\n        \\hline\n    \\end{tabular}\n\\end{table}\n\n\\begin{table}[h]\n    \\centering\n    \\caption{Cargo Data}\n    \\label{table1-25}\n    \\begin{tabular}{|c|c|c|c|c|}\n        \\hline\n        \\textbf{Cargo Type} & \\textbf{Quantity (pieces)} & \\textbf{Volume per Piece ($m^3$/piece)} & \\textbf{Weight per Piece (t/piece)} & \\textbf{Freight Rate (dollar/piece)} \\\\\n        \\hline\n        A & 600 & 10 & 8 & 1000 \\\\\n        \\hline\n        B & 1000 & 5 & 6 & 700 \\\\\n        \\hline\n        C & 800 & 7 & 4 & 600 \\\\\n        \\hline\n    \\end{tabular}\n\\end{table}\n\n For maritime safety, the actual load weight in the front, middle, and rear compartments must maintain roughly the same proportion as their respective maximum allowable loads. \n Specifically: The load weight ratios between the front/middle and rear/middle compartments must not deviate by more than 15\\% from the ratios of their respective max allowable loads. The ratio between front and rear compartments must not deviate by more than 10\\%. \n Question: How many pieces of cargo A, B, and C should be loaded in total to maximize revenue, while meeting the volume, weight, and balance constraints? \n Please formulate the linear programming model for this problem. \n',
  'cn_question': '\n一艘货轮分前、中、后三个舱位，它们的容积与最大允许载重量如表 \\ref{table1-24} 所示。\n现有三种货物待运，已知有关数据列于表 \\ref{table1-25}。\n\n\\begin{table}[h]\n    \\centering\n    \\caption{最大允许载重量与容积}\n    \\label{table1-24}\n    \\begin{tabular}{|c|c|c|}\n        \\hline\n        \\textbf{项目} & \\textbf{前舱} & \\textbf{中舱} & \\textbf{后舱} \\\\\n        \\hline\n        最大允许载重量 (t) & 2000 & 3000 & 1500 \\\\\n        \\hline\n        容积 ($m^3$) & 4000 & 5000 & 1500 \\\\\n        \\hline\n    \\end{tabular}\n\\end{table}\n\n\\begin{table}[h]\n    \\centering\n    \\caption{货物数据}\n    \\label{table1-25}\n    \\begin{tabular}{|c|c|c|c|c|}\n        \\hline\n        \\textbf{商品} & \\textbf{数量 (件)} & \\textbf{每件体积 ($m^3$/件)} & \\textbf{每件重量 (t/件)} & \\textbf{运价 (元/件)} \\\\\n        \\hline\n        A & 600 & 10 & 8 & 1000 \\\\\n        \\hline\n        B & 1000 & 5 & 6 & 700 \\\\\n        \\hline\n        C & 800 & 7 & 4 & 600 \\\\\n        \\hline\n    \\end{tabular}\n\\end{table}\n\n又为了航运安全，前、中、后舱的实际载重量大体保持各舱最大允许载重量的比例关系。\n具体要求：前、后舱分别与中舱之间载重量比例的偏差不超过 15\\%，前、后舱之间不超过 10\\%。\n问该货轮应装载 A、B、C 各多少件货物以使收入为最大？试建立这个问题的线性规划模型。\n',
  'answer': 885000.0,
  'solution_status': 'optimal',
  'domain': 'resource_allocation',
  'problem_type': 'LP',
  'difficulty': 'Medium'},
 'BWOR-006': {'id': 'BWOR-006',
  'en_question': '\n    A factory produces three types of products: I, II, and III, all of which go through two processing stages, A and B. Stage A can be performed on either machine A\\textsubscript{1} or A\\textsubscript{2}.Stage B can be carried out on any of machines B\\textsubscript{1}, B\\textsubscript{2}, or B\\textsubscript{3}. Processing capabilities: Product I can be processed on any of the A and B machines. Product II can be processed on any A machine, but only B\\textsubscript{1} can be used for stage B. Product III can only be processed on A\\textsubscript{2} for stage A and B\\textsubscript{2} for stage B. The processing time per unit, available machine hours, machine processing cost, raw material cost, and selling price are listed in Table 1-18. Task: Develop an optimal production plan to maximize the factory’s profit, taking into account machine capacity constraints, processing routes, costs, and selling prices.\n\n\\bigskip\n\n\\noindent \\textbf{Table 1-18}\n\n\\bigskip\n\n\\begin{tabular}{|c|c|c|c|c|c|}\n\\hline\n\\multirow{2}{*}{\\textbf{Machine}} & \\multicolumn{3}{c|}{\\textbf{Product}} & \\multirow{2}{*}{\\textbf{Available Hours(h)}} & \\multirow{2}{*}{\\textbf{Processing Cost (dollars/h)}} \\\\\n\\cline{2-4}\n& \\textbf{I} & \\textbf{II} & \\textbf{III} & & \\\\\n\\hline\nA\\textsubscript{1} & 5 & 10 &  & 6 000 & 0.05 \\\\\n\\hline\nA\\textsubscript{2} & 7 & 9 & 12 & 10 000 & 0.03 \\\\\n\\hline\nB\\textsubscript{1} & 6 & 8 &  & 4 000 & 0.06 \\\\\n\\hline\nB\\textsubscript{2} & 4 &  & 11 & 7 000 & 0.11 \\\\\n\\hline\nB\\textsubscript{3} & 7 &  &  & 4 000 & 0.05 \\\\\n\\hline\n\\textbf{Raw Material Cost (dollars/unit)} & 0.25 & 0.35 & 0.50 &  &  \\\\\n\\hline\n\\textbf{Selling Price (dollars/unit)} & 1.25 & 2.00 & 2.80 &  &  \\\\\n\\hline\n\\end{tabular}\n',
  'cn_question': '\n    某工厂生产 I、II、III 三种产品，都分别经 A、B 两道工序加工。设 A 工序可分别在设备 A\\textsubscript{1} 或 A\\textsubscript{2} 上完成，有 B\\textsubscript{1}、B\\textsubscript{2}、B\\textsubscript{3} 三种设备可用于完成 B 工序。已知产品 I 可在 A、B 任何一种设备上加工；产品 II 可在任何规格的 A 设备上加工，但完成 B 工序时，只能在 B\\textsubscript{1} 设备上加工；产品 III 只能在 A\\textsubscript{2} 与 B\\textsubscript{2} 设备上加工。加工单位产品所需工序时间及其他各项数据见表 1-18，试安排最优生产计划，使该厂获利最大。\n\n\\bigskip\n\n\\noindent \\textbf{表 1-18}\n\n\\bigskip\n\n\\begin{tabular}{|c|c|c|c|c|c|}\n\\hline\n\\multirow{2}{*}{\\textbf{设备}} & \\multicolumn{3}{c|}{\\textbf{产品}} & \\multirow{2}{*}{\\textbf{设备有效台时/h}} & \\multirow{2}{*}{\\textbf{设备加工费/(元/h)}} \\\\\n\\cline{2-4}\n& \\textbf{I} & \\textbf{II} & \\textbf{III} & & \\\\\n\\hline\nA\\textsubscript{1} & 5 & 10 &  & 6 000 & 0.05 \\\\\n\\hline\nA\\textsubscript{2} & 7 & 9 & 12 & 10 000 & 0.03 \\\\\n\\hline\nB\\textsubscript{1} & 6 & 8 &  & 4 000 & 0.06 \\\\\n\\hline\nB\\textsubscript{2} & 4 &  & 11 & 7 000 & 0.11 \\\\\n\\hline\nB\\textsubscript{3} & 7 &  &  & 4 000 & 0.05 \\\\\n\\hline\n\\textbf{原料费/(元/件)} & 0.25 & 0.35 & 0.50 &  &  \\\\\n\\hline\n\\textbf{售价/(元/件)} & 1.25 & 2.00 & 2.80 &  &  \\\\\n\\hline\n\\end{tabular}\n',
  'answer': 1190.566502,
  'solution_status': 'optimal',
  'domain': 'production_planning',
  'problem_type': 'LP',
  'difficulty': 'Medium'},
 'BWOR-007': {'id': 'BWOR-007',
  'en_question': '\n    \\noindent\\textbf{Example 11} In the upcoming year, the cash flow c of Tongxin Toy Factory is shown in Table 1-19. A negative sign indicates that cash outflows exceed inflows in that month, meaning the factory will need to borrow funds. There are two types of loans available: 1.Annual Loan: Borrowed at the end of the previous year, the full loan amount is received at once. Starting from the end of February, the factory must pay 1% interest each month, and then repay the principal plus the final interest payment at the end of January next year 2.Short-term Monthly Loan:Can be taken out at the beginning of any month, with both principal and interest (1.5% monthly) repaid at the beginning of the following month.When the factory has excess cash, it can make short-term deposits: Deposits are made at the beginning of the month, and withdrawn at the end of the same month, earning 0.4% interest per month. Problem: How should the factory arrange borrowing and depositing activities throughout the year to cover any cash shortfalls and maximize the total amount of cash(in thousand yuan) available at the beginning of next year? \n\n\\begin{table}[h]\n    \\centering\n    \\caption{Cash Flow Situation}\n    \\label{tab:cashflow}\n    \\begin{tabular}{ccccccccccccc}\n        \\toprule\n        Month & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12 \\\\\n        \\midrule\n        Cash Flow (thousand yuan) & -12 & -10 & -8 & -10 & -4 & 5 & -7 & -2 & 15 & 12 & -7 & 45 \\\\\n        \\bottomrule\n    \\end{tabular}\n\\end{table}\n',
  'cn_question': '\n    \\noindent\\textbf{例 11} 童心玩具厂下一年度的现金流c值如表1-19所示,表中负号表示该月现金流出大于流入,为此该厂需借款。借款有两种方式:一是于上一年年末借一年期贷款,一次获得全部贷款额,从2月底起每月还息1%,再于次年1月底归还本金和最后一次利息;二是得到短期贷款,每月初获得,于下月初归还本息,月息1.5%。当该厂有多余现金时,可短期存款,月初存人,月末取出,月息0.4%。问该厂应如何进行存贷款操作,既能弥补可能出现的负现金流,又可使下年初现金总量为最大。\n\n\\begin{table}[h]\n    \\centering\n    \\caption{现金流情况}\n    \\label{tab:cashflow}\n    \\begin{tabular}{ccccccccccccc}\n        \\toprule\n        月份 & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12 \\\\\n        \\midrule\n        现金流 (万元) & -12 & -10 & -8 & -10 & -4 & 5 & -7 & -2 & 15 & 12 & -7 & 45 \\\\\n        \\bottomrule\n    \\end{tabular}\n\\end{table}\n',
  'answer': 12.256,
  'solution_status': 'optimal',
  'domain': 'finance',
  'problem_type': 'LP',
  'difficulty': 'Medium'},
 'BWOR-008': {'id': 'BWOR-008',
  'en_question': '\n A company is responsible for transporting along four shipping routes. The known information is as follows: 1. The origin and destination cities for each route and the number of sailings per day are shown in Table 3-21. 2.The sailing times between each pair of cities are shown in Table 3-22. 3.The same type of ship is used for all routes, and each loading and unloading operation takes 1 day. Question: What is the minimum number of ships the company must deploy in order to meet the transportation requirements on all routes? \n\n\\begin{table}[h]\n    \\centering\n    \\caption{Table 3-21: Route Information}\n    \\renewcommand{\\arraystretch}{1.2}\n    \\begin{tabular}{c|c|c|c}\n        \\toprule\n        Route & Origin City & Destination City & Sailings per Day \\\\\n        \\midrule\n        1 & E & D & 3 \\\\\n        2 & B & C & 2 \\\\\n        3 & A & F & 1 \\\\\n        4 & D & B & 1 \\\\\n        \\bottomrule\n    \\end{tabular}\n\\end{table}\n\n\\begin{table}[h]\n    \\centering\n    \\caption{Table 3-22: Sailing Times Between Cities (in days)}\n    \\renewcommand{\\arraystretch}{1.2}\n    \\begin{tabular}{c|cccccc}\n        \\toprule\n        From$\\backslash$To & A & B & C & D & E & F \\\\\n        \\midrule\n        A & 0 & 1 & 2 & 14 & 7 & 7 \\\\\n        B & 1 & 0 & 3 & 13 & 8 & 8 \\\\\n        C & 2 & 3 & 0 & 15 & 5 & 5 \\\\\n        D & 14 & 13 & 15 & 0 & 17 & 20 \\\\\n        E & 7 & 8 & 5 & 17 & 0 & 3 \\\\\n        F & 7 & 8 & 5 & 20 & 3 & 0 \\\\\n        \\bottomrule\n    \\end{tabular}\n\\end{table}\n',

In [9]:
N_BATCHES = max([f[-1] for f in list_problems_versions])
N_BATCHES

19

In [13]:
output = []
for j in range(N_BATCHES+1):
    print("--------------------")
    version_tagX = f"v{j}"
    solutions = [f[1] for f in list_problems_versions if f[-1]==j]

    batch_results = []

    for s in solutions:
        file_path = Path(f"{get_project_root()}/solutions/result/{s}_{version_tagX}.json")
        
        if not file_path.exists():
            print(f"Warning: File not found - {file_path}")
            break

        with open(file_path, "r", encoding="utf-8") as f:
            exec_result_raw = json.load(f)
        exec_result = ExecutionResult(
            success=exec_result_raw["success"],
            stdout=exec_result_raw["stdout"],
            stderr=exec_result_raw["stderr"],
            returncode=exec_result_raw["returncode"]
        )

        # markdown = Path(f"solutions/markdown/{r.problem_id}_{version_tag}.md").read_text(encoding="utf-8")
        # summary_text += f"Mathematical Optimization Model:\n{markdown}\n"

        # code = Path(f"solutions/code/{r.problem_id}_{version_tag}.py").read_text(encoding="utf-8")
        # summary_text += f"Python Script:\n{code}\n"

        res = PipelineResult(
                problem_id=s,
                difficulty=problem_dict[s].get("difficulty"),
                domain=problem_dict[s].get("domain"),
                version_tag=version_tagX,
                target_answer=problem_dict[s].get("answer"),
                markdown_model="",
                python_code="",
                exec_result=exec_result
            )
        batch_results.append(res)

    all_solutions = 0
    successful_solutions = 0
    solutions = []
    for br in batch_results:
        target_answer = br.target_answer 
        all_solutions += 1
        successful_solutions += 1    
        try:
            extract_optimal_value = br.exec_result.stdout.replace("OPTIMAL_VALUE: ", "")
            extract_optimal_value = extract_optimal_value.replace("\n", " ")
            if len(extract_optimal_value.split(" "))>1:
                # print("multiple values")
                model_answer = float(extract_optimal_value.split(" ")[0])
            else: 
                model_answer = float(extract_optimal_value)
            solutions.append([target_answer, model_answer, abs(target_answer-model_answer)/abs(target_answer)])
        except:
            successful_solutions -= 1
            print(br.problem_id, f"domain:{br.domain},", f"difficulty:{br.difficulty},", f"target: {target_answer}", f"no OPTIMAL VALUE: {br.exec_result.stdout}")
    if successful_solutions > 0:
        target = [f[0] for f in solutions]
        model = [f[1] for f in solutions]
        per = [min(10.0, f[-1]) for f in solutions]
        mae = sum(per)/successful_solutions
    else: 
        mae = 10
    print(j, all_solutions, successful_solutions, mae)
    print(target, model, per)
    output.append([j, all_solutions, successful_solutions, mae])

--------------------
0 5 5 0.050288872162102274
[20.0, -700.0, 420.3957101, 43200.0, -1990500.0] [20.0, -699.9999999999973, 420.3957100591716, 43200.0, -1490000.0] [0.0, 3.897834436169693e-15, 9.711886456037356e-11, 0.0, 0.2514443607133886]
--------------------
1 5 5 0.0
[126.2, 2.336, 2500.0, 27.0, 161000.0] [126.2, 2.336, 2500.0, 27.0, 161000.0] [0.0, 0.0, 0.0, 0.0, 0.0]
--------------------
BWOR-020 domain:transportation, difficulty:Medium, target: 700.0 no OPTIMAL VALUE: NO_FEASIBLE_SOLUTION
BWOR-007 domain:finance, difficulty:Medium, target: 12.256 no OPTIMAL VALUE: NO_FEASIBLE_SOLUTION
2 5 3 6.167905692361981e-17
[1.2, 53.0, 47.0] [1.2000000000000002, 53.0, 47.0] [1.8503717077085943e-16, 0.0, 0.0]
--------------------
BWOR-067 domain:production_planning, difficulty:Medium, target: 36319.5 no OPTIMAL VALUE:
BWOR-046 domain:transportation, difficulty:Medium, target: 6100.0 no OPTIMAL VALUE: NO_FEASIBLE_SOLUTION
3 5 3 0.0
[17.0, 913.5, 1490.0] [17.0, 913.5, 1490.0] [0.0, 0.0, 0.0]
--------------------
BWOR-050 domain:assignment, difficulty:Medium, target: 126.2 no OPTIMAL VALUE:
4 5 4 0.09387755102040816
[43200.0, 1490.0, 34.0, 245.0] [43200.0, 1490.0, 34.0, 153.0] [0.0, 0.0, 0.0, 0.37551020408163266]
--------------------
5 5 5 7.795668872339385e-16
[161000.0, 646.0, -700.0, 1500.0, 245.0] [161000.0, 646.0, -699.9999999999973, 1500.0, 245.0] [0.0, 0.0, 3.897834436169693e-15, 0.0, 0.0]
--------------------
6 5 5 9.302333360112332e-05
[10750.0, 1190.566502, 47.0, 118400.0, 1490.0] [10755.0, 1190.566502463054, 47.0, 118400.0, 1490.0] [0.00046511627906976747, 3.8893584910507735e-10, 0.0, 0.0, 0.0]
--------------------
7 5 5 0.40573617029055314
[118400.0, 1190.566502, 4240.0, 4700.0, 4910500.0] [118400.0, 1190.5665024630541, 4240.0, 14234.8, 4910500.0] [0.0, 3.889360400844767e-10, 0.0, 2.0286808510638297, 0.0]
--------------------
8 5 5 0.0
[500.0, 47.0, 5.0, 4910500.0, 118400.0] [500.0, 47.0, 5.0, 4910500.0, 118400.0] [0.0, 0.0, 0.0, 0.0, 0.0]
--------------------
BWOR-020 domain:transportation, difficulty:Medium, target: 700.0 no OPTIMAL VALUE:
BWOR-025 domain:scheduling, difficulty:Medium, target: 81.0 no OPTIMAL VALUE:
9 5 3 3.3333333333333335
[646.0, 2500.0, 2.5] [646.0, 2500.0, 125000.0] [0.0, 0.0, 10.0]
--------------------
BWOR-007 domain:finance, difficulty:Medium, target: 12.256 no OPTIMAL VALUE: NO_FEASIBLE_SOLUTION
10 4 3 0.14652014652014653
[91.0, 16000.0, 370.0] [131.0, 16000.0, 370.0] [0.43956043956043955, 0.0, 0.0]
--------------------
BWOR-012 domain:blending, difficulty:Medium, target: 2500.0 no OPTIMAL VALUE: Step 1 (Min Blending Deviation): 0.0
Step 2 (Max Profit): 4500.0
11 5 4 4.5474735088646414e-17
[370.0, 10000.0, 913.5, 14650.0] [370.0, 10000.000000000002, 913.5, 14650.0] [0.0, 1.8189894035458566e-16, 0.0, 0.0]
--------------------
12 4 4 0.0
[87.0, 5.0, 2500.0, 4.0] [87.0, 5.0, 2500.0, 4.0] [0.0, 0.0, 0.0, 0.0]
--------------------
BWOR-020 domain:transportation, difficulty:Medium, target: 700.0 no OPTIMAL VALUE:
13 5 4 4.0098348519193014e-17
[708.8, 1500.0, 1490.0, 70.0] [708.8000000000001, 1500.0, 1490.0, 70.0] [1.6039339407677206e-16, 0.0, 0.0, 0.0]
--------------------
BWOR-067 domain:production_planning, difficulty:Medium, target: 36319.5 no OPTIMAL VALUE:
14 5 4 0.0
[330.0, 913.5, 155.0, 885000.0] [330.0, 913.5, 155.0, 885000.0] [0.0, 0.0, 0.0, 0.0]
--------------------
BWOR-020 domain:transportation, difficulty:Medium, target: 700.0 no OPTIMAL VALUE:
15 5 4 2.961305752320005
[91.0, 161000.0, 2.5, 20242.0] [168.0, 161.0, 125000.0, 20240.6] [0.8461538461538461, 0.999, 10.0, 6.916312617337492e-05]
--------------------
BWOR-054 domain:scheduling, difficulty:Medium, target: None no OPTIMAL VALUE: NO_FEASIBLE_SOLUTION
16 5 4 4.0098348519193014e-17
[1500.0, 708.8, 425.0, 14650.0] [1500.0, 708.8000000000001, 425.0, 14650.0] [0.0, 1.6039339407677206e-16, 0.0, 0.0]
--------------------
BWOR-025 domain:scheduling, difficulty:Medium, target: 81.0 no OPTIMAL VALUE:
17 5 4 0.0
[500.0, 2.336, 4700.0, 56000.0] [500.0, 2.336, 4700.0, 56000.0] [0.0, 0.0, 0.0, 0.0]
--------------------
BWOR-037 domain:scheduling, difficulty:Medium, target: None no OPTIMAL VALUE: NO_FEASIBLE_SOLUTION
18 5 4 0.05
[70.0, 6000000.0, 14650.0, 330.0] [84.0, 6000000.0, 14650.0, 330.0] [0.2, 0.0, 0.0, 0.0]
--------------------
BWOR-015 domain:production_planning, difficulty:Medium, target: 0.0 no OPTIMAL VALUE: OPTIMAL_VALUE: 0.0
19 5 4 3.7072880572880575
[370.0, 5.0, 2340.0, 2.5] [319.9999999999998, 28.0, 2120.0, 125000.0] [0.13513513513513575, 4.6, 0.09401709401709402, 10.0]

In [14]:
output

[[0, 5, 5, 0.050288872162102274],
 [1, 5, 5, 0.0],
 [2, 5, 3, 6.167905692361981e-17],
 [3, 5, 3, 0.0],
 [4, 5, 4, 0.09387755102040816],
 [5, 5, 5, 7.795668872339385e-16],
 [6, 5, 5, 9.302333360112332e-05],
 [7, 5, 5, 0.40573617029055314],
 [8, 5, 5, 0.0],
 [9, 5, 3, 3.3333333333333335],
 [10, 4, 3, 0.14652014652014653],
 [11, 5, 4, 4.5474735088646414e-17],
 [12, 4, 4, 0.0],
 [13, 5, 4, 4.0098348519193014e-17],
 [14, 5, 4, 0.0],
 [15, 5, 4, 2.961305752320005],
 [16, 5, 4, 4.0098348519193014e-17],
 [17, 5, 4, 0.0],
 [18, 5, 4, 0.05],
 [19, 5, 4, 3.7072880572880575]]

In [12]:
all_solutions = 0
successful_solutions = 0
solutions = []
for j, br in enumerate(batch_results):
    target_answer = br.target_answer 
    all_solutions += 1
    successful_solutions += 1    
    try:
        model_answer = float(br.exec_result.stdout.replace("OPTIMAL_VALUE: ", ""))
        solutions.append([target_answer, model_answer, abs(target_answer-model_answer)/target_answer ])
    except:
        model_answer = br.exec_result.stdout
        successful_solutions -= 1
        print(f"no OPTIMAL VALUE: model_answer")
    # print(j, target_answer, model_answer)
print(all_solutions, successful_solutions, sum([f[-1] for f in solutions])/successful_solutions)

no OPTIMAL VALUE: model_answer
5 4 12500.957288057289

In [56]:


# # 3. Create Agents for Pipeline
# formulator = LlmAgent(
#     model=MODEL,
#     name="formulator",
#     instruction=load_prompt("step1_formulation.txt")
# )

# coder = LlmAgent(
#     model=MODEL,
#     name="coder",
#     instruction=load_prompt("step3_code.txt"), 
#     tools=[filesystem_mcp]
# )

# coordinator = LlmAgent(
#     model=MODEL,
#     name="coordinator",
#     instruction=load_prompt("step5_coordinator.txt")
# )

# # # 4. Test Run
# # runner = InMemoryRunner(agent=formulator)
# # result = await runner.run_debug("Optimize production for 2 products given resource limits.", verbose=True)

In [57]:

# # 1. Pick a random problem from BWOR
# problem = load_random_problem("problems/data/test.jsonl")

# print(f"Loaded Problem ID: {problem.id}")
# print(f"Domain: {problem.domain} | Type: {problem.problem_type} | Expected Answer: {problem.answer}")
# print("-" * 50)

# # 2. Pass the question string to your Google ADK agent framework
# message = f"""
# Solve the following Operations Research problem:
# id: {problem.id}
# question: {problem.en_question}
# """

# # Run Step 1 (Formulation)
# runner = InMemoryRunner(agent=formulator)
# result1 = await runner.run_debug(message, verbose=True)

## start

In [58]:
# 3. Create Agents for Pipeline
formulator = LlmAgent(
    model=MODEL,
    name="formulator",
    instruction=load_prompt("step1_formulation.txt")
)

math_modeler = LlmAgent(
    model=MODEL,
    name="math_modeler",
    instruction=load_prompt("step2_math.txt")
)

coder = LlmAgent(
    model=MODEL,
    name="coder",
    instruction=load_prompt("step3_code.txt"),
    tools=[filesystem_mcp]
)

coordinator = LlmAgent(
    model=MODEL,
    name="coordinator",
    instruction=load_prompt("step5_coordinator.txt")
)

In [59]:

def get_event_text(events: Any) -> str:
    """Extracts text content from a list of ADK Events."""
    text_parts = []
    for event in events:
        # Check if the event contains content and parts
        if hasattr(event, "content") and event.content and hasattr(event.content, "parts"):
            for part in event.content.parts:
                if hasattr(part, "text") and part.text:
                    text_parts.append(part.text)
    return "\n".join(text_parts)

# events = await InMemoryRunner(agent=formulator).run_debug(prompt_1)

# # Extract text from the last text-bearing event
# res_text = events[-1].content.parts[0].text if events and events[-1].content else ""

In [60]:


# Load problem
problem = load_random_problem("problems/data/test.jsonl")
print(f"Problem ID: {problem.id} | Domain: {problem.domain} | Target: {problem.answer}\n Questions: {problem.en_question}\n")

Problem ID: BWOR-048 | Domain: inventory | Target: 2340.0
 Questions:
To ensure flight safety, the engines on the aircraft must be compulsorily replaced and overhauled every six months. A maintenance plant estimates that, starting from the next half-year, the engine replacement demand for a certain type of fighter aircraft over the next three years (i.e., each half-year) will be: 100, 70, 80, 120, 150, 140. When replacing an engine, it can either be replaced with a new one, or with a repaired used engine. It is known that the purchase cost of each new engine is 10 thousand yuan, while repairing used engines has two options: Fast repair: 2 thousand yuan per engine, delivered in half a year (i.e., sent in the current period, ready in the next period); Slow repair: 10,000 yuan per engine, but takes one year for delivery (i.e., sent in the current period, ready in the period after next). The plant has just received this engine replacement and repair task. It is also known that this type of fighter aircraft will be decommissioned after three years, and the engines will be scrapped after that.Question:In order to meet the maintenance demand over the next three years (six half-year periods), how many engines should be newly purchased, and how many should be sent for fast repair and slow repair in each period, so that the total maintenance cost(in thousand yuan) is minimized?

In [61]:
# Step 1: Formulation
print("--- STEP 1: Formulation ---")
prompt_1 = f"""
Analyze and formulate this Operations Research problem:
id: {problem.id}
question: {problem.en_question}
"""
res_1_events = await InMemoryRunner(agent=formulator).run_debug(prompt_1)
res_1_text = get_event_text(res_1_events)

--- STEP 1: Formulation ---
formulator > # Operations Research Formulation: Engine Replacement and Repair Planning

### 1. Decision Variables

Let $t$ denote the half-year period, where $t = 1, 2, 3, 4, 5, 6$.

*   **$x_t$**: The number of new engines purchased in period $t$.
    *   *Note:* New engines are available for immediate use in period $t$.
*   **$f_t$**: The number of used engines sent for **fast repair** in period $t$.
    *   *Note:* Fast repair takes half a year. Engines sent in period $t$ are ready for use in period $t+1$. Therefore, $f_6$ is not useful for meeting demand within the horizon (since the aircraft are decommissioned), but we will define variables for $t=1$ to $5$ for repairs that can be utilized.
*   **$s_t$**: The number of used engines sent for **slow repair** in period $t$.
    *   *Note:* Slow repair takes one year (two half-year periods). Engines sent in period $t$ are ready for use in period $t+2$. Therefore, $s_t$ is useful for $t=1$ to $4$.

*(Note: We assume that the "used engines" available for repair are those from previous replacements or existing stock. However, the problem states "When replacing an engine, it can either be replaced with a new one, or with a repaired used engine." This implies a flow of engines. To simplify the standard inventory/production planning interpretation: We must satisfy demand $D_t$ in each period using engines available in that period. Engines become available in period $t$ from:
1. New purchases made in period $t$ ($x_t$).
2. Fast repairs initiated in period $t-1$ ($f_{t-1}$).
3. Slow repairs initiated in period $t-2$ ($s_{t-2}$).
4. Initial inventory of repaired engines (assumed 0 unless specified, but usually in these problems, the "used engines" for repair come from the engines being replaced. However, a common interpretation in such textbook problems is that we have a pool of old engines that *can* be repaired. Let's look closer: "When replacing an engine... replaced with... repaired used engine." This usually implies that the engine being taken off the plane is the one being repaired. But repairs take time. So, you take an engine out in period $t$, send it for repair, and it comes back later. The engine that goes into the plane in period $t$ must come from: New purchase, or a repair that was started in a previous period.
Let's refine the availability constraints based on the lead times.
- Engines available in period $t$ to meet demand $D_t$:
  - New engines bought in period $t$: $x_t$
  - Fast repairs started in period $t-1$: $f_{t-1}$
  - Slow repairs started in period $t-2$: $s_{t-2}$

What about the source of engines for repair? The problem implies that we have a supply of "used engines" that can be sent for repair. In many such problems, the "used engines" are the ones removed from the aircraft in the current or past periods. However, if we only have the engines removed in period $t$ to repair, and they take time to return, we might have a shortfall.
Standard interpretation for this specific class of problems (often found in OR textbooks): We have a continuous supply of "core" engines that can be either bought new or repaired. The constraint is that the total number of engines in the system is fixed, or we are minimizing the cost of acquiring/repairing to meet demand.
Actually, a simpler and more common interpretation for "how many should be sent for repair" is that we are deciding the *mix* of sourcing.
Let's assume that for every engine that needs to be replaced, we choose a source.
Source 1: Buy New (Cost 10, Lead time 0).
Source 2: Fast Repair (Cost 2, Lead time 1 period).
Source 3: Slow Repair (Cost 10, Lead time 2 periods).

Wait, the cost of Slow Repair is 10,000 yuan? "Slow repair: 10,000 yuan per engine". The new engine cost is 10 thousand yuan. So Slow Repair costs the same as New? That seems odd, but I must follow the prompt. "Fast repair: 2 thousand yuan... Slow repair: 10,000 yuan". Yes.
And "delivered in half a year... Slow repair... takes one year".

Crucial Point: Where do the engines for repair come from?
If the problem implies that we have a large stock of used engines available for repair at the start, then we just balance demand.
If the problem implies that the engines for repair are the ones *removed* from the planes, then we have a recycling loop.
However, the question asks "how many engines should be newly purchased, and how many should be sent for fast repair and slow repair in each period". This phrasing suggests we are scheduling the *actions* of purchasing and sending for repair.
Usually, in such problems, the constraint is simply that the sum of engines arriving in period $t$ must meet the demand $D_t$. The "used engines" sent for repair are assumed to be available from a pool (perhaps from previous decommissions or a steady state) unless specified otherwise. Given the "decommissioned after three years" note, it might imply that engines from previous periods become available for repair.
Let's assume the standard "Production Planning with Lag" model where:
Available in period $t$ = $x_t + f_{t-1} + s_{t-2}$.
Constraint: $x_t + f_{t-1} + s_{t-2} \ge D_t$ (for $t=1..6$).
We need to handle the initial conditions. $f_0 = 0, s_{-1} = 0, s_0 = 0$.
Also, we must ensure that we don't send more engines for repair than we have available "cores". But often in these simplified problems, the "availability of cores for repair" is not the binding constraint, or it's assumed there is an initial stock of cores equal to the total demand, or that the "used engines" are just a resource we can tap into.
*Alternative Interpretation*: The engines removed in period $t$ are the ones that *can* be sent for repair.
If we replace an engine in period $t$, we take one out. We can then decide to send that specific engine for fast or slow repair.
If we send it for fast repair, it returns in $t+1$.
If we send it for slow repair, it returns in $t+2$.
If we don't repair it, it's scrapped (or kept as spare, but the problem says "replaced with... repaired used engine", implying the source is the repair queue).
This creates a dynamic inventory of "engines in repair".
Let's look at the costs.
New: 10.
Fast Repair: 2 (Lead 1).
Slow Repair: 10 (Lead 2).
Since Slow Repair cost (10) = New Cost (10), and it has a longer lead time, Slow Repair is strictly dominated by New Purchase unless there is a scarcity of new engines or a specific constraint on new purchases. Or perhaps I misread? "Slow repair: 10,000 yuan". "Purchase cost... 10 thousand yuan". They are equal.
However, Fast Repair is much cheaper (2). So we should prioritize Fast Repair.
But Fast Repair has a 1-period lag.
If we can only repair the engines we *just* removed, we have a limit on how many we can repair.
Let $R_t$ be the number of engines removed in period $t$. $R_t = D_t$ (since 1 out, 1 in).
The engines removed in period $t$ can be sent for:
- Fast Repair (returns $t+1$)
- Slow Repair (returns $t+2$)
- Scrap (no return)
We also buy new engines $x_t$ (returns $t$).
The engines available to *install* in period $t$ are:
1. New engines bought in $t$: $x_t$
2. Fast repairs started in $t-1$: $f_{t-1}$
3. Slow repairs started in $t-2$: $s_{t-2}$
Total Installed = $x_t + f_{t-1} + s_{t-2}$.
This must equal Demand $D_t$.
So, $x_t + f_{t-1} + s_{t-2} = D_t$.
What limits $f_t$ and $s_t$?
The engines sent for repair in period $t$ must come from the engines removed in period $t$.
So, $f_t + s_t \le D_t$ (You can't send more for repair than you have removed).
Also $f_t, s_t, x_t \ge 0$.

This interpretation (Recycling the removed engines) is physically consistent with "When replacing an engine... it can... be replaced with... a repaired used engine". It implies the used engines are the ones taken off.

Let's check the feasibility.
Period 1:
Demand $D_1 = 100$.
Available: $x_1 + f_0 + s_{-1} = x_1$. (Assuming no initial repairs in pipeline).
So $x_1 = 100$.
Engines removed in P1: 100.
We can send $f_1, s_1$ for repair. Constraint: $f_1 + s_1 \le 100$.

Period 2:
Demand $D_2 = 70$.
Available: $x_2 + f_1 + s_0 = x_2 + f_1$.
So $x_2 + f_1 = 70$.
Engines removed in P2: 70.
Constraint: $f_2 + s_2 \le 70$.

Period 3:
Demand $D_3 = 80$.
Available: $x_3 + f_2 + s_1 = 80$.
Engines removed in P3: 80.
Constraint: $f_3 + s_3 \le 80$.

Period 4:
Demand $D_4 = 120$.
Available: $x_4 + f_3 + s_2 = 120$.
Engines removed in P4: 120.
Constraint: $f_4 + s_4 \le 120$.

Period 5:
Demand $D_5 = 150$.
Available: $x_5 + f_4 + s_3 = 150$.
Engines removed in P5: 150.
Constraint: $f_5 + s_5 \le 150$.
Note: $s_5$ returns in P7, which is outside the horizon. So $s_5$ is useless for meeting demand 1-6. We should probably set $s_5=0$ or just not include it in the objective/constraints for benefit. Since we want to minimize cost, and slow repair costs 10 (same as new), and new is instant, we would never choose slow repair over new if we have the choice, UNLESS we are forced to use repairs to avoid buying new? No, cost is the same. But wait, if we buy new, we pay 10. If we slow repair, we pay 10. Why would we slow repair? Maybe to keep the "core" in the system? But the problem says engines are scrapped after 3 years.
Actually, if Cost(Slow) = Cost(New), and LeadTime(Slow) > LeadTime(New), Slow Repair is dominated. We should never use Slow Repair unless there is a constraint limiting New Purchases. There is no such constraint.
However, Fast Repair (Cost 2) is much cheaper. We should maximize Fast Repair usage.
The bottleneck for Fast Repair is that it takes 1 period.
In Period 1, we must buy 100 new. We remove 100. We can send up to 100 for Fast Repair.
In Period 2, we need 70. We have $f_1$ available. We can use up to 70 of them. We buy the rest new.
This looks like a valid formulation.

Let's refine the variables to be strictly what is asked: "how many engines should be newly purchased, and how many should be sent for fast repair and slow repair in each period".

**Decision Variables:**
*   $x_t$: Number of new engines purchased in period $t$, for $t=1,\dots,6$.
*   $f_t$: Number of engines sent for fast repair in period $t$, for $t=1,\dots,6$.
    *   (Note: Engines sent in period $t$ are available in period $t+1$).
    *   Engines sent in period 6 are available in period 7 (outside horizon), so $f_6$ does not help meet demand 1-6. It only incurs cost. Since cost > 0, optimal $f_6$ will be 0.
*   $s_t$: Number of engines sent for slow repair in period $t$, for $t=1,\dots,6$.
    *   (Note: Engines sent in period $t$ are available in period $t+2$).
    *   Engines sent in period 5 are available in period 7 (outside).
    *   Engines sent in period 6 are available in period 8 (outside).
    *   So $s_5, s_6$ do not help meet demand 1-6. Optimal $s_5=s_6=0$.

**Objective Function:**
Minimize Total Cost $Z$.
$Z = \sum_{t=1}^{6} (10 x_t + 2 f_t + 10 s_t)$

**Constraints:**

1.  **Demand Satisfaction (Flow Balance):**
    The number of engines installed in period $t$ must equal the demand $D_t$.
    Engines installed in period $t$ come from:
    - New purchases in period $t$: $x_t$
    - Fast repairs initiated in period $t-1$: $f_{t-1}$
    - Slow repairs initiated in period $t-2$: $s_{t-2}$

    Equations:
    -   **Period 1:** $x_1 = D_1 = 100$
    -   **Period 2:** $x_2 + f_1 = D_2 = 70$
    -   **Period 3:** $x_3 + f_2 + s_1 = D_3 = 80$
    -   **Period 4:** $x_4 + f_3 + s_2 = D_4 = 120$
    -   **Period 5:** $x_5 + f_4 + s_3 = D_5 = 150$
    -   **Period 6:** $x_6 + f_5 + s_4 = D_6 = 140$

2.  **Repair Source Constraint (Availability of Used Engines):**
    The number of engines sent for repair in period $t$ cannot exceed the number of engines removed (replaced) in period $t$.
    Engines removed in period $t$ = Demand $D_t$ (since 1 is replaced for 1).
    Engines sent for repair in period $t$ = $f_t + s_t$.

    Equations:
    -   $f_1 + s_1 \le D_1 = 100$
    -   $f_2 + s_2 \le D_2 = 70$
    -   $f_3 + s_3 \le D_3 = 80$
    -   $f_4 + s_4 \le D_4 = 120$
    -   $f_5 + s_5 \le D_5 = 150$
    -   $f_6 + s_6 \le D_6 = 140$

3.  **Non-negativity:**
    $x_t, f_t, s_t \ge 0$ for all $t=1,\dots,6$.
    (Integer constraints are implied for physical engines, but in LP formulation, we usually state non-negativity. If integer programming is required, add integrality. Given the numbers, integer solutions are likely expected, but standard OR formulation often starts with LP. I will specify non-negative integers as it's a counting problem).

    *Self-Correction on Slow Repair:*
    As noted, $s_t$ has the same cost as $x_t$ but longer lead time.
    In Period 3, we need $x_3 + f_2 + s_1 = 80$.
    $s_1$ comes from Period 1 removals.
    Cost of $s_1$ is 10. Cost of $x_3$ is 10.
    Is there any reason to use $s_1$?
    If we use $s_1$, we must have sent an engine for slow repair in P1.
    If we use $x_3$, we buy new in P3.
    Since costs are identical, and there are no capacity constraints on new purchases, $s_1$ is indifferent to $x_3$ in terms of cost. However, using $s_1$ consumes a "repair slot" from P1.
    Actually, looking at the objective: $10 x_t + 10 s_t$.
    If we substitute $x_3 = 80 - f_2 - s_1$, the cost becomes $10(80 - f_2 - s_1) + 2 f_2 + 10 s_1 + \dots$
    $= 800 - 10 f_2 - 10 s_1 + 2 f_2 + 10 s_1 + \dots$
    $= 800 - 8 f_2 + \dots$
    The $s_1$ terms cancel out in the total cost calculation relative to the demand?
    Let's check total cost contribution for satisfying one unit of demand in P3.
    Option A: Buy New ($x_3$). Cost 10.
    Option B: Use Fast Repair from P2 ($f_2$). Cost 2 (paid in P2).
    Option C: Use Slow Repair from P1 ($s_1$). Cost 10 (paid in P1).

    Wait, the cost is paid in the period the action is taken.
    Objective: Min $\sum (10 x_t + 2 f_t + 10 s_t)$.

    If we choose $s_1=1$ (to help P3), we pay 10 in P1.
    If we choose $x_3=1$ (to help P3), we pay 10 in P3.
    Total cost is the same.
    However, choosing $s_1=1$ requires that $f_1+s_1 \le 100$.
    Choosing $x_3=1$ does not affect P1 constraints.
    Since $s_1$ occupies capacity in P1 repair slots, and $x_3$ does not, and they cost the same, it is generally "safer" or equivalent to use New Engines ($x$) instead of Slow Repairs ($s$) if Fast Repairs ($f$) are not sufficient, because it frees up repair slots for potentially cheaper Fast Repairs in other periods?
    Actually, if we use $s_1$, we *cannot* use that engine for $f_1$.
    If we use $f_1$, it helps P2. Cost 2.
    If we use $s_1$, it helps P3. Cost 10.
    If we don't use it for repair, we buy new for P2 (Cost 10) and P3 (Cost 10).

    Let's compare strategies for one engine removed in P1:
    1. Send for Fast Repair ($f_1=1$):
       - Helps P2.
       - P2 needs 1 less New Engine.
       - Cost: 2 (for repair) + 0 (saved new in P2? No, we just buy less new).
       - Compared to buying new for P2 (Cost 10), we save 8.
    2. Send for Slow Repair ($s_1=1$):
       - Helps P3.
       - P3 needs 1 less New Engine.
       - Cost: 10 (for repair) + 0 (saved new in P3).
       - Compared to buying new for P3 (Cost 10), we save 0.

    Therefore, Fast Repair is strictly better than Slow Repair in terms of cost savings relative to buying new, because Fast Repair cost (2) < New Cost (10), while Slow Repair cost (10) = New Cost (10).
    So, we should maximize $f_t$ and minimize $s_t$ (likely 0).

    This insight confirms the formulation is correct, but $s_t$ will likely be 0 in the optimal solution.

### Final Structured Output

# Operations Research Formulation: Engine Maintenance Planning

### 1. Decision Variables

Let $t$ represent the half-year period, where $t \in \{1, 2, 3, 4, 5, 6\}$.

*   **$x_t$**: The number of new engines purchased in period $t$.
*   **$f_t$**: The number of used engines sent for **fast repair** in period $t$.
    *   *Note:* These engines are available for use in period $t+1$.
*   **$s_t$**: The number of used engines sent for **slow repair** in period $t$.
    *   *Note:* These engines are available for use in period $t+2$.

All variables are non-negative integers.

### 2. Objective Function

**Minimize** the total maintenance cost (in thousand yuan):

$$
\text{Minimize } Z = \sum_{t=1}^{6} \left( 10 x_t + 2 f_t + 10 s_t \right)
$$

*   Cost of new engine: 10
*   Cost of fast repair: 2
*   Cost of slow repair: 10

### 3. Operational Constraints

**A. Demand Satisfaction Constraints**
The total number of engines available for installation in period $t$ must exactly meet the demand $D_t$.
Engines available in period $t$ are composed of new purchases in $t$, fast repairs initiated in $t-1$, and slow repairs initiated in $t-2$.
*(Note: $f_0 = s_0 = s_{-1} = 0$)*

*   **Period 1:**
    $$ x_1 = 100 $$
*   **Period 2:**
    $$ x_2 + f_1 = 70 $$
*   **Period 3:**
    $$ x_3 + f_2 + s_1 = 80 $$
*   **Period 4:**
    $$ x_4 + f_3 + s_2 = 120 $$
*   **Period 5:**
    $$ x_5 + f_4 + s_3 = 150 $$
*   **Period 6:**
    $$ x_6 + f_5 + s_4 = 140 $$

**B. Repair Source Constraints**
The number of engines sent for repair in any period $t$ cannot exceed the number of engines removed (replaced) in that same period $t$. Since the demand is met by replacing 1 engine for 1 engine, the number of engines removed in period $t$ is equal to $D_t$.

*   **Period 1:**
    $$ f_1 + s_1 \le 100 $$
*   **Period 2:**
    $$ f_2 + s_2 \le 70 $$
*   **Period 3:**
    $$ f_3 + s_3 \le 80 $$
*   **Period 4:**
    $$ f_4 + s_4 \le 120 $$
*   **Period 5:**
    $$ f_5 + s_5 \le 150 $$
*   **Period 6:**
    $$ f_6 + s_6 \le 140 $$

**C. Non-negativity and Integrality**
$$ x_t, f_t, s_t \ge 0, \quad \forall t \in \{1, \dots, 6\} $$
$$ x_t, f_t, s_t \in \mathbb{Z} $$

In [62]:
# Step 2: Math Modeling
print("--- STEP 2: Mathematical Model ---")
prompt_2 = f"Problem ID:{problem.id}\nProblem:\n{problem.en_question}\n\nFormulation:\n{res_1_text}"
res_2_events = await InMemoryRunner(agent=math_modeler).run_debug(prompt_2)
res_2_text = get_event_text(res_2_events)

--- STEP 2: Mathematical Model ---
math_modeler > To formulate this engine replacement and repair planning problem, we define the following mathematical model.

### 1. Index Sets and Parameters

**Index Sets:**
*   $T = \{1, 2, 3, 4, 5, 6\}$: The set of half-year periods over the 3-year horizon.

**Parameters:**
*   $D_t$: The number of engines requiring replacement in period $t$.
    *   $D = [100, 70, 80, 120, 150, 140]$
*   $C_N = 10$: The cost (in thousand yuan) to purchase one new engine.
*   $C_F = 2$: The cost (in thousand yuan) for fast repair of one used engine.
*   $C_S = 10$: The cost (in thousand yuan) for slow repair of one used engine.
*   $L_F = 1$: The lead time (in periods) for fast repair.
*   $L_S = 2$: The lead time (in periods) for slow repair.

### 2. Decision Variables

Let the decision variables represent the actions taken in each period $t \in T$:

*   $x_t$: The number of **new engines purchased** in period $t$.
    *   Domain: $x_t \in \mathbb{Z}^+$ (non-negative integers)
*   $f_t$: The number of used engines **sent for fast repair** in period $t$.
    *   Domain: $f_t \in \mathbb{Z}^+$ (non-negative integers)
    *   *Note:* Engines sent in period $t$ become available for installation in period $t+1$.
*   $s_t$: The number of used engines **sent for slow repair** in period $t$.
    *   Domain: $s_t \in \mathbb{Z}^+$ (non-negative integers)
    *   *Note:* Engines sent in period $t$ become available for installation in period $t+2$.

*(Note: For periods where repairs are initiated but the resulting engines would be available after the horizon ends (i.e., $f_6$ and $s_5, s_6$), these variables will naturally be zero in the optimal solution as they incur cost without contributing to meeting the demand within $T$. However, they are formally included in the summation for completeness, or can be restricted to 0. Here, we include them in the constraints for periods $t=1$ to $6$ as defined by the source availability.)*

### 3. Objective Function

Minimize the total maintenance cost $Z$ (in thousand yuan):

$$
\text{Minimize } Z = \sum_{t=1}^{6} (C_N x_t + C_F f_t + C_S s_t)
$$

Substituting the parameter values:

$$
Z = 10 \sum_{t=1}^{6} x_t + 2 \sum_{t=1}^{6} f_t + 10 \sum_{t=1}^{6} s_t
$$

### 4. Operational Constraints

**A. Demand Satisfaction Constraints (Flow Balance)**
The total number of engines available for installation in period $t$ must exactly equal the demand $D_t$. The sources of engines available in period $t$ are:
1.  New engines purchased in period $t$ ($x_t$).
2.  Fast repairs initiated in the previous period $t-1$ ($f_{t-1}$).
3.  Slow repairs initiated in the period $t-2$ ($s_{t-2}$).

Assuming no initial inventory of engines in repair or stock at $t=0$ (i.e., $f_0=0, s_0=0, s_{-1}=0$):

*   **Period 1:**
    $$ x_1 = 100 $$
*   **Period 2:**
    $$ x_2 + f_1 = 70 $$
*   **Period 3:**
    $$ x_3 + f_2 + s_1 = 80 $$
*   **Period 4:**
    $$ x_4 + f_3 + s_2 = 120 $$
*   **Period 5:**
    $$ x_5 + f_4 + s_3 = 150 $$
*   **Period 6:**
    $$ x_6 + f_5 + s_4 = 140 $$

**B. Repair Source Constraints (Availability of Used Engines)**
The number of engines sent for repair (fast or slow) in any period $t$ cannot exceed the number of engines removed from the aircraft in that same period. Since one engine is removed for every replacement, the total engines removed in period $t$ is $D_t$.

*   **Period 1:**
    $$ f_1 + s_1 \le 100 $$
*   **Period 2:**
    $$ f_2 + s_2 \le 70 $$
*   **Period 3:**
    $$ f_3 + s_3 \le 80 $$
*   **Period 4:**
    $$ f_4 + s_4 \le 120 $$
*   **Period 5:**
    $$ f_5 + s_5 \le 150 $$
*   **Period 6:**
    $$ f_6 + s_6 \le 140 $$

**C. Non-negativity and Integrality**
$$ x_t, f_t, s_t \ge 0 \quad \forall t \in T $$
$$ x_t, f_t, s_t \in \mathbb{Z} \quad \forall t \in T $$

In [66]:
from IPython.display import display, Markdown
display(Markdown(res_2_text))

To formulate this engine replacement and repair planning problem, we define the following mathematical model.

### 1. Index Sets and Parameters

**Index Sets:**
*   $T = \{1, 2, 3, 4, 5, 6\}$: The set of half-year periods over the 3-year horizon.

**Parameters:**
*   $D_t$: The number of engines requiring replacement in period $t$.
    *   $D = [100, 70, 80, 120, 150, 140]$
*   $C_N = 10$: The cost (in thousand yuan) to purchase one new engine.
*   $C_F = 2$: The cost (in thousand yuan) for fast repair of one used engine.
*   $C_S = 10$: The cost (in thousand yuan) for slow repair of one used engine.
*   $L_F = 1$: The lead time (in periods) for fast repair.
*   $L_S = 2$: The lead time (in periods) for slow repair.

### 2. Decision Variables

Let the decision variables represent the actions taken in each period $t \in T$:

*   $x_t$: The number of **new engines purchased** in period $t$.
    *   Domain: $x_t \in \mathbb{Z}^+$ (non-negative integers)
*   $f_t$: The number of used engines **sent for fast repair** in period $t$.
    *   Domain: $f_t \in \mathbb{Z}^+$ (non-negative integers)
    *   *Note:* Engines sent in period $t$ become available for installation in period $t+1$.
*   $s_t$: The number of used engines **sent for slow repair** in period $t$.
    *   Domain: $s_t \in \mathbb{Z}^+$ (non-negative integers)
    *   *Note:* Engines sent in period $t$ become available for installation in period $t+2$.

*(Note: For periods where repairs are initiated but the resulting engines would be available after the horizon ends (i.e., $f_6$ and $s_5, s_6$), these variables will naturally be zero in the optimal solution as they incur cost without contributing to meeting the demand within $T$. However, they are formally included in the summation for completeness, or can be restricted to 0. Here, we include them in the constraints for periods $t=1$ to $6$ as defined by the source availability.)*

### 3. Objective Function

Minimize the total maintenance cost $Z$ (in thousand yuan):

$$
\text{Minimize } Z = \sum_{t=1}^{6} (C_N x_t + C_F f_t + C_S s_t)
$$

Substituting the parameter values:

$$
Z = 10 \sum_{t=1}^{6} x_t + 2 \sum_{t=1}^{6} f_t + 10 \sum_{t=1}^{6} s_t
$$

### 4. Operational Constraints

**A. Demand Satisfaction Constraints (Flow Balance)**
The total number of engines available for installation in period $t$ must exactly equal the demand $D_t$. The sources of engines available in period $t$ are:
1.  New engines purchased in period $t$ ($x_t$).
2.  Fast repairs initiated in the previous period $t-1$ ($f_{t-1}$).
3.  Slow repairs initiated in the period $t-2$ ($s_{t-2}$).

Assuming no initial inventory of engines in repair or stock at $t=0$ (i.e., $f_0=0, s_0=0, s_{-1}=0$):

*   **Period 1:**
    $$ x_1 = 100 $$
*   **Period 2:**
    $$ x_2 + f_1 = 70 $$
*   **Period 3:**
    $$ x_3 + f_2 + s_1 = 80 $$
*   **Period 4:**
    $$ x_4 + f_3 + s_2 = 120 $$
*   **Period 5:**
    $$ x_5 + f_4 + s_3 = 150 $$
*   **Period 6:**
    $$ x_6 + f_5 + s_4 = 140 $$

**B. Repair Source Constraints (Availability of Used Engines)**
The number of engines sent for repair (fast or slow) in any period $t$ cannot exceed the number of engines removed from the aircraft in that same period. Since one engine is removed for every replacement, the total engines removed in period $t$ is $D_t$.

*   **Period 1:**
    $$ f_1 + s_1 \le 100 $$
*   **Period 2:**
    $$ f_2 + s_2 \le 70 $$
*   **Period 3:**
    $$ f_3 + s_3 \le 80 $$
*   **Period 4:**
    $$ f_4 + s_4 \le 120 $$
*   **Period 5:**
    $$ f_5 + s_5 \le 150 $$
*   **Period 6:**
    $$ f_6 + s_6 \le 140 $$

**C. Non-negativity and Integrality**
$$ x_t, f_t, s_t \ge 0 \quad \forall t \in T $$
$$ x_t, f_t, s_t \in \mathbb{Z} \quad \forall t \in T $$

In [63]:
# Step 3: Code Generation
prompt_3 = f"Problem ID: {problem.id}\nConvert this math model into OR-Tools Python code:\n{res_2_text}"
res_3_events = await InMemoryRunner(agent=coder).run_debug(prompt_3)
res_3_text = get_event_text(res_3_events)

coder > Let me first check the workspace directory structure to determine where to save the script.


coder > Now I'll create the Python script that translates this engine replacement and repair planning model into OR-Tools code.


coder > Let me verify the file was written correctly:


coder > The script is saved and verified. Here's a summary of the translation:

### File: `/mnt/datafast/Development/or-llm-agent/solutions/engine_replacement_planning.py`

**Key design decisions:**

| Aspect | Choice | Rationale |
|---|---|---|
| **Solver** | `SCIP` (MILP) | All variables are integer (`IntVar`), so a MILP solver is required |
| **Variables** | `x[0..5]`, `f[0..5]`, `s[0..5]` as `IntVar(0, ∞)` | 18 integer decision variables covering all 6 periods |
| **Objective** | Minimize `10·Σx + 2·Σf + 10·Σs` | Direct transcription of the cost formula |
| **Demand constraints** | 6 equality constraints | Each period's available engines (new + fast from t−1 + slow from t−2) must exactly meet demand |
| **Source constraints** | 6 inequality constraints | `f_t + s_t ≤ D_t` — you can't send more engines to repair than were removed |

**Expected optimal logic (by inspection):**
- Fast repair costs 2 vs. new at 10 → always prefer fast repair when possible
- Slow repair costs 10 = new engine cost → indifferent, but slow repair has a 2-period delay
- The solver will push as many engines into fast repair as the source constraints allow, filling the rest with new purchases

The script prints a per-period table of all decision variables, a cost breakdown, and the total objective value upon solving.

In [64]:
# for event in res_3_events:
#     print(event)
#     print("-----------")
print(res_3_text)

Let me first check the workspace directory structure to determine where to save the script.


Now I'll create the Python script that translates this engine replacement and repair planning model into OR-Tools code.


Let me verify the file was written correctly:


The script is saved and verified. Here's a summary of the translation:

### File: `/mnt/datafast/Development/or-llm-agent/solutions/engine_replacement_planning.py`

**Key design decisions:**

| Aspect | Choice | Rationale |
|---|---|---|
| **Solver** | `SCIP` (MILP) | All variables are integer (`IntVar`), so a MILP solver is required |
| **Variables** | `x[0..5]`, `f[0..5]`, `s[0..5]` as `IntVar(0, ∞)` | 18 integer decision variables covering all 6 periods |
| **Objective** | Minimize `10·Σx + 2·Σf + 10·Σs` | Direct transcription of the cost formula |
| **Demand constraints** | 6 equality constraints | Each period's available engines (new + fast from t−1 + slow from t−2) must exactly meet demand |
| **Source constraints** | 6 inequality constraints | `f_t + s_t ≤ D_t` — you can't send more engines to repair than were removed |

**Expected optimal logic (by inspection):**
- Fast repair costs 2 vs. new at 10 → always prefer fast repair when possible
- Slow repair costs 10 = new engine cost → indifferent, but slow repair has a 2-period delay
- The solver will push as many engines into fast repair as the source constraints allow, filling the rest with new purchases

The script prints a per-period table of all decision variables, a cost breakdown, and the total objective value upon solving.

In [ ]:
# Step 4: Execution
print("--- STEP 4: Execution ---")
exec_res = run_generated_code(res_3_text)

In [ ]:
# Step 5: Coordinator Debug Loop (if needed)
if not exec_res.success:
    print("⚠️ Code failed. Entering Step 5 Debugger...")
    prompt_5 = f"""
    Code failed execution.
    
    Generated Code:
    {res_3_text}
    
    Error Traceback:
    {exec_res.stderr}
    """
    res_5_events = await InMemoryRunner(agent=coordinator).run_debug(prompt_5, verbose=False)
    print("Coordinator Diagnosis:\n", get_event_text(res_5_events))
else:
    print("✅ Solver Output:\n", exec_res.stdout)

In [25]:
# Step 1: Formulation
prompt_1 = f"Analyze and formulate this OR problem:\n{problem.en_question}"
res_1 = await InMemoryRunner(agent=formulator).run_debug(prompt_1)

# Step 3: Code Generation (directly from Step 1)
prompt_3 = f"Problem:\n{problem.en_question}\n\nFormulation:\n{res_1.output_text}"
res_3 = await InMemoryRunner(agent=coder).run_debug(prompt_3)

# Step 4: Run Code
exec_res = run_generated_code(res_3.output_text)

❌ FAILED (BWOR-017): Expected 300.0, got 91.0